document.body.style.backgroundColor="skyblue";
document.body.style.textAlign="center";
let a=document.createElement("h1");
a.style.backgroundColor="white";
a.innerHTML="STUDENT DETAILS";
document.body.appendChild(a);
let up=document.createElement("button");
up.innerHTML="Upload photo";
document.body.appendChild(up);
let b=document.createElement("p");
b.innerHTML=" Student Name :";
b.style.backgroundColor="white";
document.body.appendChild(b);
let c=document.createElement("input");
c.innerHTML="";
document.body.appendChild(c);
let d=document.createElement("p");
d.innerHTML=" Roll No :";
d.style.backgroundColor="white";
document.body.appendChild(d);
let e=document.createElement("input");
e.innerHTML="";
document.body.appendChild(e);
let f=document.createElement("p");
f.innerHTML=" Date of Birth :";
f.style.backgroundColor="white";
document.body.appendChild(f);
let g=document.createElement("input");
g.type="date";
document.body.appendChild(g);
let h=document.createElement("p");
h.innerHTML="Email :";
h.type="email";
h.style.backgroundColor="white";
document.body.appendChild(h);
let i=document.createElement("input");
i.innerHTML="";
document.body.appendChild(i);
let j=document.createElement("p");
j.innerHTML="Mobile No :";
j.style.backgroundColor="white";
document.body.appendChild(j);
let k=document.createElement("input");
k.type="tel";
document.body.appendChild(k);
let l=document.createElement("p");
l.innerHTML=" Father Name :";
l.style.backgroundColor="white";
document.body.appendChild(l);
let m=document.createElement("input");
m.innerHTML="";
document.body.appendChild(m);
let o=document.createElement("p");
o.innerHTML="Address :";
o.style.backgroundColor="white";
document.body.appendChild(o);
let p=document.createElement("input");
p.innerHTML="";
document.body.appendChild(p);
let br=document.createElement("br");
let q=document.createElement("button");
q.innerHTML="Submit";
document.body.appendChild(q);
q.appendChild(br);