# Generated by Django 5.2.4 on 2025-07-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_details_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
