# Generated by Django 5.2.4 on 2025-07-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_details_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
